name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/cd relax-together-backend
            git pull origin dev
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            sudo nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &